#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rblox/runner'

runner = Rblox::Runner.new

case ARGV.size
when 0
  runner.run_prompt
when 1
  runner.run_file(ARGV[0])
else
  puts 'Usage: rblox [script]'
  exit 64
end
