module Rblox
  class Callable
    @arity: Integer

    attr_reader arity: Integer

    def initialize: (Integer arity) -> void

    def call: (Interpreter interpreter, Array[untyped] arguments) -> untyped
  end
end
