module Rblox
  class Callable
    @arity: Integer
    @block: ^(?Interpreter interpreter, ?Array[untyped] arguments) -> untyped

    attr_reader arity: Integer

    def initialize: (Integer arity) { (?Interpreter interpreter, ?Array[untyped] arguments) -> untyped } -> void

    def call: (?Interpreter interpreter, ?Array[untyped] arguments) -> untyped

    def self.function: (Stmt::FunctionStmt declaration, ?Environment? closure) -> Callable
  end
end
