module Rblox
  class Error < StandardError
  end

  class ParseError < Error
  end

  class RuntimeError < Error
    @token: Token

    attr_reader token: Token

    def initialize: (Token token, String message) -> void
  end

  class Return < Error
    @value: untyped

    attr_reader value: untyped

    def initialize: (untyped value) -> void
  end
end
