module Rblox
  class Token
    attr_reader type: Symbol
    attr_reader lexeme: String
    attr_reader literal: Object?
    attr_reader line: Integer

    def initialize: (Symbol type, String lexeme, Object? literal, Integer line) -> void
                  | (type: Symbol, lexeme: String, literal: Object?, line: Integer) -> void
  end
end
